<script setup>
    import VueMultiselect from 'vue-multiselect'
    import AppLayout from '@/Layouts/AppLayout.vue'
    import AddServiceModal from '@/Components/AddServiceModal.vue'
    import { Head, Link, router } from '@inertiajs/vue3'
    import { computed, reactive, ref, watch } from 'vue'

    const props = defineProps({
        service_units: Object,
        sub_units: Object,
        user: Object,
    })

    const form = reactive({
        service_id: null,
        unit_id: null,
    })

    // Search and service filter. Every unit is already on the page, so both
    // work on the loaded list without another request.
    const search = ref('')
    const service_filter = ref('')

    const services = computed(() => props.service_units?.data ?? [])
    const unitsOf = (service) => (Array.isArray(service.units) ? service.units : [])
    const total_units = computed(() => services.value.reduce((count, service) => count + unitsOf(service).length, 0))

    // A unit matches on its own name or on the name of one of its sub-units.
    const matchUnit = (unit, term) => {
        if ((unit.unit_name ?? '').toLowerCase().includes(term)) return { unit, sub_unit: null }
        const sub_unit = (Array.isArray(unit.sub_units) ? unit.sub_units : [])
            .find((item) => (item.sub_unit_name ?? '').toLowerCase().includes(term))
        return sub_unit ? { unit, sub_unit: sub_unit.sub_unit_name } : null
    }

    const groups = computed(() => {
        const term = search.value.trim().toLowerCase()
        return services.value
            .filter((service) => service_filter.value === '' || service.id === service_filter.value)
            .map((service) => {
                const units = unitsOf(service)
                // A service that matches by its own name keeps all of its units.
                const keep_all = !term || (service.services_name ?? '').toLowerCase().includes(term)
                const rows = keep_all
                    ? units.map((unit) => ({ unit, sub_unit: null }))
                    : units.map((unit) => matchUnit(unit, term)).filter(Boolean)
                return { service, rows, total: units.length }
            })
            .filter((group) => !term || group.rows.length)
    })

    const shown_units = computed(() => groups.value.reduce((count, group) => count + group.rows.length, 0))
    const is_filtered = computed(() => search.value.trim() !== '' || service_filter.value !== '')

    const clearFilters = () => {
        search.value = ''
        service_filter.value = ''
    }

    const unitCountLabel = (group) => {
        const units = group.total === 1 ? 'unit' : 'units'
        return group.rows.length === group.total ? `${group.total} ${units}` : `${group.rows.length} of ${group.total} ${units}`
    }

    // Splits a name around the search term so the matching part can be marked.
    const highlight = (text) => {
        const name = text ?? ''
        const term = search.value.trim()
        const at = term ? name.toLowerCase().indexOf(term.toLowerCase()) : -1
        if (at < 0) return [{ text: name, hit: false }]
        return [
            { text: name.slice(0, at), hit: false },
            { text: name.slice(at, at + term.length), hit: true },
            { text: name.slice(at + term.length), hit: false },
        ]
    }

    const show_modal = ref(false)
    const action_clicked = ref('')
    const selected_service = ref({})

    const rating = async (service_id, unit_id) => {
        form.service_id = service_id
        form.unit_id = unit_id
        router.get('/csi', form, { preserveState: true })
    }

    const all_service_unit_rating = async () => {
        form.form_type = 'all units'
        router.get('/csi/all-units', form, { preserveState: true })
    }

    const goViewPage = async (service_id, unit_id) => {
        form.service_id = service_id
        form.unit_id = unit_id
        router.get('/csi/view', form, { preserveState: true })
    }

    const showServiceModal = async (is_show, action, service) => {
        show_modal.value = is_show
        action_clicked.value = action
        if (service) {
            selected_service.value = service
        }
    }

    // The blank paper form, generated by the app (reports/csf-manual-form.blade.php).
    const openPDF = () => {
        window.open('/csf/manual-form', '_blank')
    }
</script>

<template>
    <AppLayout title="Service Units">
        <template #header>
            <div class="page-heading">
                <h2 class="page-heading-title">Service Units</h2>
                <p class="page-heading-subtitle mb-0">Manage service units and launch rating/report actions.</p>
            </div>
        </template>

        <div class="container-fluid py-4 libraries-page">
            <div class="row justify-content-center">
                <div class="col-12 col-lg-11">
                    <div class="card shadow-lg border-0" style="border-radius: 20px; overflow: hidden;">
                        <div class="card-header text-white position-relative overflow-hidden d-flex flex-wrap gap-3 justify-content-between align-items-center" style="background: linear-gradient(135deg, #667eea 0%, #764ba2 50%, #f093fb 100%); padding: 20px 25px;">
                            <div class="position-absolute top-0 end-0 p-3 opacity-25">
                                <i class="ri-building-4-line" style="font-size: 80px;"></i>
                            </div>
                            <div class="position-relative">
                                <h3 class="card-title mb-0">
                                    <i class="ri-building-4-line me-2"></i>
                                    Service Units Management
                                </h3>
                                <p class="mb-0 mt-1 opacity-75" style="font-size: 0.9rem;">Configure and manage service units</p>
                            </div>
                            <div class="d-flex flex-wrap gap-3 align-items-center position-relative">
                                <button
                                    v-if="user.account_type == 'admin'"
                                    @click="showServiceModal(true, 'add_new_service', null)"
                                    class="btn btn-light btn-sm fw-semibold"
                                    style="border-radius: 20px;"
                                >
                                    <i class="ri-add-line me-1"></i>
                                    Add New Service
                                </button>
                                <button
                                    @click="all_service_unit_rating()"
                                    class="btn btn-warning btn-sm fw-semibold"
                                    style="border-radius: 20px;"
                                >
                                    <i class="ri-file-chart-line me-1"></i>
                                    All Unit Ratings
                                </button>
                                <button
                                    @click="openPDF()"
                                    class="btn btn-success btn-sm fw-semibold"
                                    style="border-radius: 20px;"
                                >
                                    <i class="ri-printer-line me-1"></i>
                                    CSF Form (Manual)
                                </button>
                            </div>
                        </div>

                        <!-- Search and service filter -->
                        <div class="unit-toolbar d-flex flex-wrap align-items-center gap-2">
                            <div class="unit-search">
                                <div class="input-group input-group-sm">
                                    <span class="input-group-text bg-white border-0"><i class="ri-search-line text-muted"></i></span>
                                    <input
                                        type="text"
                                        class="form-control border-0 shadow-none"
                                        placeholder="Search units or sub-units..."
                                        aria-label="Search units or sub-units"
                                        autocomplete="off"
                                        v-model="search"
                                        @keydown.esc="search = ''"
                                    >
                                    <button
                                        v-if="search"
                                        @click="search = ''"
                                        type="button"
                                        class="btn btn-clear-search border-0"
                                        aria-label="Clear search"
                                    >
                                        <i class="ri-close-line"></i>
                                    </button>
                                </div>
                            </div>
                            <select class="form-select form-select-sm unit-service-filter" aria-label="Show one service" v-model="service_filter">
                                <option value="">All services ({{ total_units }} units)</option>
                                <option v-for="service in services" :key="service.id" :value="service.id">
                                    {{ service.services_name }} ({{ unitsOf(service).length }})
                                </option>
                            </select>
                            <div class="ms-auto d-flex align-items-center gap-2">
                                <span class="unit-result-count" aria-live="polite">
                                    Showing {{ shown_units }} of {{ total_units }} units
                                </span>
                                <button v-if="is_filtered" @click="clearFilters()" type="button" class="btn btn-sm btn-outline-secondary btn-clear-filters">
                                    <i class="ri-filter-off-line me-1"></i>
                                    Clear
                                </button>
                            </div>
                        </div>

                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table class="table table-hover mb-0" style="min-width: 600px;">
                                    <thead class="table-dark" style="background: linear-gradient(135deg, #2d3748 0%, #4a5568 100%);">
                                        <tr>
                                            <th class="text-center" style="width: 80px;">#</th>
                                            <th>Unit Name</th>
                                            <th class="text-center" style="width: 200px;">Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <template
                                            v-for="group in groups"
                                            :key="group.service.id"
                                        >
                                            <!-- Service Header Row -->
                                            <tr class="table-primary service-header-row">
                                                <td colspan="3" class="fw-bold fs-5">
                                                    <div class="d-flex align-items-center">
                                                        <div class="icon-circle me-2" style="width: 36px; height: 36px; border-radius: 50%; background: linear-gradient(135deg, rgba(79, 172, 254, 0.3) 0%, rgba(0, 242, 254, 0.3) 100%); display: flex; align-items: center; justify-content: center;">
                                                            <i class="ri-service-line text-info"></i>
                                                        </div>
                                                        <span>{{ group.service.services_name }}</span>
                                                        <span class="badge unit-count-badge ms-2">{{ unitCountLabel(group) }}</span>
                                                        <button
                                                            v-if="user.account_type == 'admin'"
                                                            @click="showServiceModal(true, 'add_new_unit', group.service)"
                                                            class="btn btn-success btn-sm ms-3"
                                                            style="border-radius: 15px;"
                                                        >
                                                            <i class="ri-add-line"></i>
                                                        </button>
                                                    </div>
                                                </td>
                                            </tr>

                                            <!-- Unit Rows -->
                                            <tr
                                                v-for="({ unit, sub_unit }, unitIndex) in group.rows"
                                                :key="unit.id"
                                                class="align-middle table-row-animated"
                                            >
                                                <td class="text-center fw-bold text-muted">
                                                    {{ unitIndex + 1 }}
                                                </td>
                                                <td>
                                                    <div class="d-flex align-items-center">
                                                        <div class="icon-circle me-2" style="width: 32px; height: 32px; border-radius: 50%; background: linear-gradient(135deg, rgba(79, 172, 254, 0.2) 0%, rgba(0, 242, 254, 0.2) 100%); display: flex; align-items: center; justify-content: center;">
                                                            <i class="ri-building-line text-blue"></i>
                                                        </div>
                                                        <div>
                                                            <span class="fw-semibold text-dark">
                                                                <template v-for="(part, partIndex) in highlight(unit.unit_name)" :key="partIndex">
                                                                    <mark v-if="part.hit" class="unit-hit">{{ part.text }}</mark>
                                                                    <template v-else>{{ part.text }}</template>
                                                                </template>
                                                            </span>
                                                            <!-- Shown when the search matched a sub-unit, not the unit's own name -->
                                                            <div v-if="sub_unit" class="unit-sub-match">
                                                                Sub-unit:
                                                                <template v-for="(part, partIndex) in highlight(sub_unit)" :key="partIndex">
                                                                    <mark v-if="part.hit" class="unit-hit">{{ part.text }}</mark>
                                                                    <template v-else>{{ part.text }}</template>
                                                                </template>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td class="text-center">
                                                    <div class="btn-group btn-group-sm" role="group">
                                                        <button
                                                            @click="goViewPage(group.service.id, unit.id)"
                                                            class="btn btn-primary"
                                                            style="border-radius: 15px 0 0 15px;"
                                                            :disabled="user.account_type == 'user' && user.unit_id != unit.id"
                                                        >
                                                            <i class="ri-eye-line me-1"></i>
                                                            View
                                                        </button>
                                                        <button
                                                            @click="rating(group.service.id, unit.id)"
                                                            class="btn btn-warning"
                                                            style="border-radius: 0 15px 15px 0;"
                                                            :disabled="user.account_type == 'user' && user.unit_id != unit.id"
                                                        >
                                                            <i class="ri-star-line me-1"></i>
                                                            Rating
                                                        </button>
                                                    </div>
                                                </td>
                                            </tr>
                                        </template>

                                        <!-- Nothing matched the search -->
                                        <tr v-if="!groups.length">
                                            <td colspan="3" class="text-center unit-empty">
                                                <i class="ri-search-eye-line d-block mb-2"></i>
                                                <p class="fw-semibold mb-1">No units found</p>
                                                <p class="text-muted mb-3">
                                                    <template v-if="search.trim()">Nothing matches "{{ search.trim() }}".</template>
                                                    <template v-else>There are no services to show.</template>
                                                </p>
                                                <button v-if="is_filtered" @click="clearFilters()" type="button" class="btn btn-sm btn-primary" style="border-radius: 15px;">
                                                    Clear search and filter
                                                </button>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <AddServiceModal
            :value="show_modal"
            :action-clicked="action_clicked"
            :selected-service="selected_service"
            @input="showServiceModal"
        />
    </AppLayout>
</template>

<style src="vue-multiselect/dist/vue-multiselect.css"></style>

<style scoped>
.libraries-page {
    background: linear-gradient(135deg, #f5f9ff 0%, #edf3fb 100%);
    min-height: 100vh;
}

.page-heading-title {
    margin: 0;
    color: #12243a;
    font-size: 1.25rem;
    font-weight: 700;
}

.page-heading-subtitle {
    color: #5b7088;
    font-size: 0.9rem;
}

.card {
    border: 1px solid #d8e5f5 !important;
    box-shadow: 0 10px 26px rgba(21, 59, 112, 0.08) !important;
}

.card-header {
    background: linear-gradient(90deg, #1b365d, #2a568f) !important;
}

.service-header-row {
    background: #eaf2ff !important;
}

/* Search and service filter */
.unit-toolbar {
    padding: 14px 25px;
    background: #f4f8ff;
    border-bottom: 1px solid #d8e5f5;
}

.unit-search {
    flex: 1 1 260px;
    max-width: 420px;
}

.unit-search .input-group {
    overflow: hidden;
    border: 1px solid #c5d6ec;
    border-radius: 25px;
    background: #fff;
}

.unit-search .input-group:focus-within,
.unit-service-filter:focus {
    border-color: #2a568f;
    box-shadow: 0 0 0 3px rgba(42, 86, 143, 0.15);
}

.btn-clear-search {
    color: #5b7088;
    background: #fff;
}

.btn-clear-search:hover {
    color: #12243a;
}

.unit-service-filter {
    flex: 0 1 360px;
    width: auto;
    border-color: #c5d6ec;
    border-radius: 25px;
}

.unit-result-count {
    color: #5b7088;
    font-size: 0.85rem;
    white-space: nowrap;
}

.btn-clear-filters {
    border-radius: 20px;
}

.unit-count-badge {
    color: #1f3b6e;
    background: rgba(31, 59, 110, 0.12);
    font-size: 0.75rem;
    font-weight: 600;
}

.unit-hit {
    /* no padding: it would open a gap in the middle of the word */
    padding: 0;
    border-radius: 2px;
    background: #ffe69c;
    color: inherit;
}

.unit-sub-match {
    color: #5b7088;
    font-size: 0.8rem;
}

.unit-empty {
    padding: 48px 16px;
}

.unit-empty i {
    color: #9db3cf;
    font-size: 2.5rem;
}

.table-dark th {
    background: #1f3b6e !important;
    border-color: #365988 !important;
}

.table-hover tbody tr:hover {
    background-color: rgba(33, 94, 154, 0.06) !important;
}

.btn-primary {
    background: linear-gradient(135deg, #1f6db3, #1a4f89);
    border: none;
}

.btn-warning {
    background: linear-gradient(135deg, #c47b2f, #a65c27);
    border: none;
    color: #fff;
}

.btn-success {
    background: linear-gradient(135deg, #2e9b6a, #1f7f67);
    border: none;
}
</style>
